name: NoirPVP
version: 0.1.3
main: com.github.margeobur.noirpvp.NoirPVPPlugin
author: margeobur
description: PVP management for Noirland, 2018+
depend: [GriefPrevention]
commands:
  innocent:
    description: Casts a vote in the current trial, declaring the defendant as INNOCENT.
    usage: /innocent.
    permission: noirpvp.vote
  guilty:
    description: Casts a vote in the current trial, declaring the defendant as GUILTY.
    usage: /guilty
    permission: noirpvp.vote
  crime:
    description: Displays information about a player's crime status.
    usage: Use "/crime" to see how many crime marks you have. Use "/crime top" to see the players with the most crimes. Use "/crime <player name>" to see how many crimes a particular player has.
permissions:
  noirpvp.vote:
    description: Allows players to use /innocent and /guilty to vote in trials.