name: NoirPVP
version: 0.1.91
main: com.github.margeobur.noirpvp.NoirPVPPlugin
author: margeobur
description: PVP management for Noirland, 2018+
depend: [GriefPrevention]
commands:
  innocent:
    description: Casts a vote in the current trial, declaring the defendant as INNOCENT.
    usage: /innocent.
    permission: noirpvp.vote
  guilty:
    description: Casts a vote in the current trial, declaring the defendant as GUILTY.
    usage: /guilty
    permission: noirpvp.vote
  crime:
    description: Displays information about a player's crime status.
    usage: Use "/crime" to see how many crime marks you have. Use "/crime top" to see the players with the most crimes. Use "/crime <player name>" to see how many crimes a particular player has.
  njail:
    description: Allows admins to detain a player and initiate a vote to enact discipline. Allows players to vote in a trial
    usage: Use "/njail <playername> <reason>" to jail a player. Use "/njail addcell" to set the current location as warp point for criminals
  nunjail:
    description: Allows admins to remove players from jail and end their sentence early
    usage: Use "/nunjail <playername> to cancel a player's sentence
  nkick:
    description: Allows players to vote for a player to be kicked
    usage: /nkick to cast a vote to kick the player on trial
  nban:
    description: Allows players to vote for a player to be banned
    usage: /nban to cast a vote to ban the player on trial
  setdock:
    description: Sets the location that alleged criminals will be teleported to when their trials begin
    usage: Use "/setdock" to set the current location as THE warp-point for the defendants in trials
    permission: noirpvp.setlocations
  setrelease:
    description: Sets the location that players found innocent will be teleported to after a trial
    usage: Use "/setrelease" to set your current location as THE release point for innocent players
    permission: noirpvp.setlocations
permissions:
  noirpvp.vote:
    description: Allows players to use /innocent, /guilty,  to vote in trials. (/nban and /nkick for admin trials)
  noirpvp.jail:
    description: Given to admins\mods so that they can use /njail <playername> <reason>
  noirpvp.setlocations:
    description: Given to admins so that they can add locations for the jail and trials